### ISSUE TITLE
get_empty_room without natten

### ISSUE THREAD

**Issue by adrianblazeusz** [Lavreniuk/generative-interior-design#3]
I'm having a difficult time installing natte on windows. Where does the script need this library? I want to replace it with some substitute

**Comment by melgor** [comment]
as I remember, it is used by `OneFormer` model https://github.com/Lavreniuk/generative-interior-design/blob/main/get_empty_room/get_empty_room.py#L16C58-L16C68

If you change to a different model, like https://gitlab.aicrowd.com/bartosz_ludwiczuk/generative-interior-design-challenge-2024-starter-kit/-/blob/master/models/controlnet_baseline.py?ref_type=heads#L44 it may also work, but quality of segmentation masks would be lower.

**Comment by adrianblazeusz** [comment]
Thank you!
